# -*- coding: utf-8 -*-
"""Task-2 calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qXL-AnfvrBeoWvD0pKdigLQzEwzU3bOU

Here's a simple python program for a basic calculator:
"""

def calculator():
  print("simple calculator")
  print("choose an operation")
  print("1. Addition(+)")
  print("2. subtraction (-)")
  print("3. multiplication(*)")
  print("4. Division(/)")
  operation=input("Enter the number of the operation(1/2/3/4): ")
  if operation not in ['1','2','3','4']:
      print("Invalid choice! please choose a valid operation.")
      return
  try:
      num1 = float(input("Enter the first number: "))
      num2 = float(input("Enter the second number: "))
  except ValueError:
      print("Invalid input! please enter numeric values")
      return
  if operation == '1' :
      result = num1 + num2
      print(f"The result of {num1} + {num2} is: {result}")
  elif operation == '2':
      result = num1 - num2
      print(f"The result of {num1} - {num2} is: {result}")
  elif operation == '3':
       result = num1 * num2
       print(f"The result of {num1} * {num2} is: {result}")
  elif operation == '4':
      if num2 !=0:
         result = num1 /num2
         print(f"The result of {num1} / {num2} is: {result}")
      else:
         print("Error:Division by zero is not allowed.")

#Run the calculator
calculator()

"""How it works:
1.The program displays a menu with basic arithmetic operations.
2.The user inputs their choice and two numbers.
3.The program performs the operation and displays the result.
4.Input validation ensures the program handles invalid entries gracefully.
"""